// array of dictionaries that contain each question and answer set
    // const questionList = [
    //   {question : `It's your day off. How do you want to spend it?`, 
    //     answers: ['Plotting revenge on my enemies', 
    //             'Snuggled up next to the fire with a book', 
    //             'Out and about with my best friends', 
    //             'Getting high and going to Target', 
    //             'Spending time with family',
    //             'On a hike',
    //             'Exploring new places in my neighborhood', 
    //             `Day off? I don't take days off.`]},
    //   {question : 'What is your favorite color?', 
    //     answers: ['Yellow', 
    //             'Red', 
    //             'Blue', 
    //             'Purple',
    //             'Black']},
    //   {question : 'Where would you most want to go on vacation?', 
    //     answers: ['NYC', 
    //             'Nashville', 
    //             'London', 
    //             'A cabin in the woods', 
    //             'Wherever my boo is 🥹']},
    //   {question: `What is your preferred method of revenge?`, 
    //     answers: ['Glow up', 
    //             'Lobotomy', 
    //             'Murder', 
    //             'Torture',
    //             'Ghosting', 
    //             'Public humiliation',
    //             'Karma',
    //             'Getting the last word']},
    //   {question : 'Choose your character.', 
    //     answers: ['Cowgirl', 
    //             'Witch', 
    //             'Loner', 
    //             'Princess', 
    //             'Popstar']},
    //   {question : 'What is your go-to musical genre?', 
    //     answers: ['Indie', 
    //             'Country', 
    //             'Pop', 
    //             'Rock', 
    //             'EDM',
    //             'Rap']},
    //   {question : `What's your toxic trait?`, 
    //     answers: ['Overthinking',
    //             'Impulsiveness',
    //             'Indecisiveness',
    //             'Defensiveness',
    //             'Over-idealizing people',
    //             'Isolating myself',
    //             'Escapism',
    //             'Perfectionism',
    //             'People-pleasing',
    //             'Rumination']},
    //   {question : `It's cold outside. What do you reach for?`, 
    //     answers: ['A classic denim jacket', 
    //             'A cozy scarf', 
    //             'My favorite fall flannel', 
    //             'My leather jacket', 
    //             'An old cardigan',
    //             'A fur coat']},
    //   {question : 'How would you describe your most palpable relationship trauma?', 
    //     answers: ['Unspoken regrets',
    //             'Intense heartache',
    //             'Betrayal and defiance',
    //             'Idealistic disillusionment',
    //             'Quiet heartbreak',
    //             'Longing in solitude',
    //             'Innocent heartbreak',]},
    //   {question : 'How do you like to listen to music?', 
    //     answers: ['Alone with a glass of wine', 
    //             'Singing along with a group of friends']}
    // ];